import ollama
import pandas as pd
from sklearn.metrics import f1_score, classification_report
import json
import os
from collections import defaultdict
import random
from tqdm import tqdm
import warnings
import re

warnings.filterwarnings("ignore")

MODEL_NAME = "qwen3-coder:30b" 
CHECKPOINT_FILE = "predictions_checkpoint.csv"
FEW_SHOT_COUNT = 5  
BATCH_SIZE = 1

def tokenize_code(code):
    # strip strings and comments
    code = re.sub(r'\"\"\".*?\"\"\"', '', code, flags=re.DOTALL)
    code = re.sub(r"\'\'\'.*?\'\'\'", '', code, flags=re.DOTALL)
    code = re.sub(r'\".*?\"', '', code)
    code = re.sub(r"\'.*?\'", '', code)
    code = re.sub(r'#.*$', '', code, flags=re.MULTILINE)
    code = re.sub(r'//.*$', '', code, flags=re.MULTILINE)
    code = re.sub(r'/\*.*?\*/', '', code, flags=re.DOTALL)
    
    tokens = re.findall(r'[a-zA-Z_][a-zA-Z0-9_]*|[+\-*/%=<>!&|^~]+|[\[\]{}();,.]', code)
    return set(t.lower() for t in tokens)


def jaccard(s1, s2):
    """Jaccard similarity between two sets"""
    if not s1 or not s2:
        return 0.0
    return len(s1 & s2) / len(s1 | s2)


def create_detection_prompt(code_snippet, language, few_shot_examples):
    """Build the prompt with few-shot examples"""
    prompt = f"""You are an expert code analyst specializing in distinguishing human-written code from AI-generated code.

Your task: Analyze the following code snippet and determine if it was written by a human (0) or generated by AI (1).

Key indicators to examine:
1. **Commenting style**: AI often uses overly verbose or template-like comments
2. **Variable naming**: AI may use overly descriptive or generic names (e.g., 'result', 'temp', 'helper')
3. **Code structure**: AI tends to follow very standard patterns, humans may have quirks
4. **Error handling**: AI often includes comprehensive error handling, humans may skip it
5. **Whitespace & formatting**: AI typically has perfectly consistent spacing
6. **Algorithm efficiency**: AI may choose textbook solutions over practical shortcuts
7. **Edge cases**: AI often handles edge cases explicitly that humans might ignore
8. **Documentation**: AI frequently over-documents or uses formal docstrings

Here are examples from the training set:

"""
    
    for i, example in enumerate(few_shot_examples, 1):
        author = "Human" if example['label'] == 0 else "AI"
        prompt += f"""--- Example {i} ({example['language']}) ---
    Code:
    ```{example['language'].lower()}
    {example['code'][:500]}...
    ```
    Analysis: This code was written by {author}.
    Label: {example['label']}

    """
        
        prompt += f"""--- Now analyze this code ({language}) ---
    Code:
    ```{language.lower()}
    {code_snippet}
    ```

    Provide your analysis and respond with ONLY a single digit:
    - 0 if the code is human-written
    - 1 if the code is AI-generated

    Your response (0 or 1):"""
    
    return prompt

def extract_prediction(response_text):
    """Parse 0 or 1 from model output"""
    response_text = response_text.strip()
    for char in response_text:
        if char in ['0', '1']:
            return int(char)
    
    # fallback: check for keywords
    lower_response = response_text.lower()
    if 'human' in lower_response and 'ai' not in lower_response:
        return 0
    elif 'ai' in lower_response or 'machine' in lower_response or 'generated' in lower_response:
        return 1
    
    print(f"Warning: Unclear response '{response_text}', defaulting to 1")
    return 1

def load_checkpoint():
    if os.path.exists(CHECKPOINT_FILE):
        df = pd.read_csv(CHECKPOINT_FILE)
        print(f"Loaded {len(df)} existing predictions from checkpoint")
        return df
    return pd.DataFrame(columns=['ID', 'label'])

def save_checkpoint(predictions_df):
    predictions_df.to_csv(CHECKPOINT_FILE, index=False)

def prepare_few_shot_examples(train_data, test_code, count=5):
    """Pick similar examples from train set using token overlap"""
    test_tokens = tokenize_code(test_code)
    
    # score all training samples by similarity
    similarities = []
    for idx, ex in enumerate(train_data):
        sim = jaccard(test_tokens, tokenize_code(ex['code']))
        similarities.append((idx, sim, ex))
    
    similarities.sort(key=lambda x: x[1], reverse=True)
    top_candidates = similarities[:count * 10]
    
    # split by label for balanced selection
    human_examples = [(idx, sim, ex) for idx, sim, ex in top_candidates if ex['label'] == 0]
    ai_examples = [(idx, sim, ex) for idx, sim, ex in top_candidates if ex['label'] == 1]
    
    selected = []
    human_count = min(count // 2, len(human_examples))
    ai_count = min(count - human_count, len(ai_examples))
    
    if human_count < count // 2 and ai_examples:
        ai_count = min(count - human_count, len(ai_examples))
    if ai_count < count - human_count and human_examples:
        human_count = min(count - ai_count, len(human_examples))
    
    for i in range(human_count):
        if i < len(human_examples):
            selected.append(human_examples[i][2])
    
    for i in range(ai_count):
        if i < len(ai_examples):
            selected.append(ai_examples[i][2])
    
    if len(selected) < count:
        for idx, sim, ex in top_candidates:
            if ex not in selected:
                selected.append(ex)
                if len(selected) >= count:
                    break
    
    random.shuffle(selected)
    return selected[:count]

def run_inference(test_data, train_data, checkpoint_df):
    """Run model on test samples with checkpointing"""
    results = []
    processed_ids = set(checkpoint_df['ID'].tolist()) if not checkpoint_df.empty else set()
    
    print(f"Starting inference on {len(test_data)} samples...")
    print(f"Already processed: {len(processed_ids)} samples")
    
    for idx, sample in enumerate(tqdm(test_data)):
        sample_id = sample['ID']
        
        # skip already done
        if sample_id in processed_ids:
            existing_pred = checkpoint_df[checkpoint_df['ID'] == sample_id]['label'].values[0]
            results.append({'ID': sample_id, 'label': existing_pred})
            continue
        
        try:
            few_shot_examples = prepare_few_shot_examples(train_data, sample['code'], FEW_SHOT_COUNT)
            prompt = create_detection_prompt(sample['code'], sample['language'], few_shot_examples)
            
            response = ollama.chat(
                model=MODEL_NAME,
                messages=[
                    {'role': 'system', 'content': 'You are an expert at analyzing code to detect AI-generated patterns. Always respond with only 0 or 1.'},
                    {'role': 'user', 'content': prompt}
                ],
                options={'temperature': 0.1, 'num_predict': 10}
            )
            
            prediction = extract_prediction(response['message']['content'])
            results.append({'ID': sample_id, 'label': prediction})
            
            # checkpoint every 10
            if (idx + 1) % 10 == 0:
                temp_df = pd.DataFrame(results)
                all_predictions = pd.concat([checkpoint_df, temp_df], ignore_index=True)
                save_checkpoint(all_predictions)
                print(f"\nCheckpoint saved at {idx + 1} samples")
            
        except Exception as e:
            print(f"\nError processing sample {sample_id}: {str(e)}")
            results.append({'ID': sample_id, 'label': 1})
            continue
    
    return pd.DataFrame(results)

def evaluate_predictions(predictions_df, test_data):
    """Compute and print metrics"""
    test_df = pd.DataFrame(test_data)
    merged = test_df.merge(predictions_df, on='ID', suffixes=('_true', '_pred'))
    
    y_true = merged['label_true'].values
    y_pred = merged['label_pred'].values
    macro_f1 = f1_score(y_true, y_pred, average='macro')
    
    print("\n" + "="*50)
    print("EVALUATION RESULTS")
    print("="*50)
    print(f"Macro F1 Score: {macro_f1:.4f}")
    print("\nDetailed Classification Report:")
    print(classification_report(y_true, y_pred, target_names=['Human', 'AI']))
    
    print("\nPer-Language Performance:")
    for lang in merged['language'].unique():
        lang_data = merged[merged['language'] == lang]
        lang_f1 = f1_score(lang_data['label_true'], lang_data['label_pred'], average='macro')
        print(f"  {lang}: Macro F1 = {lang_f1:.4f}")
    
    return macro_f1

def main():
    print("Loading dataset from parquet files in `data/`...")

    # Data directory is ../../data/ relative to this script's location
    script_dir = os.path.dirname(os.path.abspath(__file__))
    data_dir = os.path.join(script_dir, "..", "..", "data")
    train_path = os.path.join(data_dir, "train.parquet")
    test_path = os.path.join(data_dir, "final_test.parquet")

    if not os.path.exists(train_path):
        print(f"Error: train file not found at {train_path}")
        return
    if not os.path.exists(test_path):
        print(f"Error: test file not found at {test_path}")
        return

    try:
        train_df = pd.read_parquet(train_path)
        test_df = pd.read_parquet(test_path)
    except Exception as e:
        print(f"Error reading parquet files: {e}")
        return

    train_data = train_df.to_dict(orient='records')
    test_data = test_df.to_dict(orient='records')

    print(f"Train samples: {len(train_data)}")
    print(f"Test samples: {len(test_data)}")
    
    try:
        ollama.list()
        print(f"\nOllama is running. Using model {MODEL_NAME}...")
    except Exception as e:
        print(f"Error: Ollama not accessible: {e}")
        return
    
    checkpoint_df = load_checkpoint()
    predictions_df = run_inference(test_data, train_data, checkpoint_df)
    
    final_predictions = pd.concat([checkpoint_df, predictions_df], ignore_index=True)
    final_predictions = final_predictions.drop_duplicates(subset=['ID'], keep='last')
    
    output_file = "final_predictions.csv"
    final_predictions.to_csv(output_file, index=False)
    print(f"\nFinal predictions saved to {output_file}")
    
    test_df_for_eval = pd.DataFrame(test_data)
    if 'label' in test_df_for_eval.columns:
        evaluate_predictions(final_predictions, test_data)
    else:
        print("\nNo ground truth labels in test set. Skipping evaluation.")
    
    print("\nDone!")

if __name__ == "__main__":
    main()